# Generated by Django 2.1.4 on 2020-05-05 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=32, verbose_name='站点名称')),
            ],
        ),
        migrations.CreateModel(
            name='WaterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH', models.CharField(max_length=32, verbose_name='PH')),
                ('NTU', models.CharField(max_length=32, verbose_name='浑浊度')),
                ('oxygen', models.CharField(max_length=32, verbose_name='溶解氧')),
                ('tem', models.CharField(max_length=32, verbose_name='水温')),
                ('ele', models.CharField(max_length=32, verbose_name='电导率')),
                ('chlorine', models.CharField(max_length=32, verbose_name='余氯')),
                ('site', models.IntegerField(choices=[(1, '正常'), (2, '异常'), (0, '离线')], verbose_name='站点状态')),
                ('cTime', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='上报日期')),
            ],
            options={
                'verbose_name': '水务数据信息',
                'verbose_name_plural': '水务数据信息',
            },
        ),
        migrations.DeleteModel(
            name='WaterSite',
        ),
        migrations.AddField(
            model_name='site',
            name='water',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waters', to='api.WaterData', verbose_name='水务数据'),
        ),
    ]
