# Generated by Django 2.1.4 on 2020-05-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200505_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waterdata',
            old_name='PH',
            new_name='pH',
        ),
    ]
