# Generated by Django 2.1.4 on 2020-05-14 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200509_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.CharField(max_length=32, verbose_name='PH合格率')),
                ('NTU', models.CharField(max_length=32, verbose_name='浊度合格率')),
                ('chlorine', models.CharField(max_length=32, verbose_name='余氯合格率')),
                ('time', models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='上报日期')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Site', verbose_name='站点信息')),
            ],
            options={
                'verbose_name': '水务数据统计',
                'verbose_name_plural': '水务数据统计',
            },
        ),
    ]
